### ISSUE TITLE
TFMG 0.9.0d Bugs (Cable block, Radial engine) 

### ISSUE THREAD

**Issue by KaleTinvald** [DrMango14/Create-The_Factory_Must_Grow#100]
1. Tested on Forge server. If cable block gets exploded with any kind of explosion, a big propeller model gets spawned at the location of each player. This model is clippable-through and isn't used anywhere. Disappears after player's death, but appears at players location (but doesn't move with player) after reconnecting.
2. Radial engine ponderings are invisible

**Comment by HydrogenC** [comment]
I can also reproduce the issue that Radial engine ponders cannot be rendered correctly.

**Comment by KaleTinvald** [comment]
Problem with propeller model was resolved with last update 0.9.1c, but thing with radial engine left. 
Tested a lot more. Propeller bug appeared after exploding powered cable blocks with any explosives.

**Comment by Alainx277** [comment]
Radial engine ponder is still broken in 0.9.3-1.20.1

```
[15:09:56] [Render thread/ERROR] [co.si.cr.Create/]: Failed to read ponder schematic: tfmg:ponder/radial_engines.nbt
java.io.EOFException: null
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:?] {}
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:?] {}
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:?] {}
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:?] {}
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:?] {}
	at com.simibubi.create.foundation.ponder.PonderRegistry.loadSchematic(PonderRegistry.java:119)
```
