### ISSUE TITLE
Model Error fireproof_brick_reinforcement.json

### ISSUE THREAD

**Issue by BigFatWizard** [DrMango14/Create-The_Factory_Must_Grow#22]
`[23:12:15] [Worker-Main-7/ERROR] [minecraft/ModelManager]: Failed to load model tfmg:models/block/fireproof_brick_reinforcement.json
com.google.gson.JsonSyntaxException: Missing texture, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:127) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.block.model.BlockElementFace$Deserializer.m_111370_(BlockElementFace.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockElementFace$Deserializer.deserialize(BlockElementFace.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockElementFace$Deserializer.deserialize(BlockElementFace.java:48) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2388!/:?] {}
	at net.minecraft.client.renderer.block.model.BlockElement$Deserializer.m_111339_(BlockElement.java:143) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockElement$Deserializer.m_111325_(BlockElement.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockElement$Deserializer.deserialize(BlockElement.java:83) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockElement$Deserializer.deserialize(BlockElement.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2388!/:?] {}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2388!/:?] {}
	at net.minecraft.client.renderer.block.model.BlockModel$Deserializer.m_111506_(BlockModel.java:376) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockModel$Deserializer.deserialize(BlockModel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:53) ~[forge-1.20.1-47.2.17-universal.jar%23371!/:?] {re:classloading}
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:38) ~[forge-1.20.1-47.2.17-universal.jar%23371!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2388!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.block.model.BlockModel.m_111461_(BlockModel.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_246478_(ModelManager.java:110) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}`

**Comment by DrMango14** [comment]
outdated
