### ISSUE TITLE
Issue with Create interactive

### ISSUE THREAD

**Issue by slasherbane** [DrMango14/Create-The_Factory_Must_Grow#34]
HI ^^ , i try to launch my game with the new  create interactive mod but it throw me that error : 

[03janv.2024 11:32:38.188] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[03janv.2024 11:32:38.597] [modloading-worker-0/INFO] [plus.dragons.createdragonlib.DragonLib/]: Create: Dragon Lib 1.3.3 has initialized, ready to support your Create add-ons!
[03janv.2024 11:32:38.781] [modloading-worker-0/INFO] [create_new_age/]: Hello 1.20.1 Create!
[03janv.2024 11:32:39.175] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 47.2.17, for MC 1.20.1 with MCP 20230612.114412
[03janv.2024 11:32:39.175] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v47.2.17 Initialized
[03janv.2024 11:32:39.438] [modloading-worker-0/WARN] [mixin/]: Method overwrite conflict for this in create_interactive-common.mixins.json:AbstractContraptionEntityAccessor, previously written by org.valkyrienskies.create_interactive.mixin.MixinAbstractContraptionEntity. Skipping method.
[03janv.2024 11:32:39.529] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: tfmg, class com.drmangotea.tfmg.CreateTFMG
java.lang.ExceptionInInitializerError: null
	at com.drmangotea.tfmg.registry.TFMGBlocks.<clinit>(TFMGBlocks.java:253) ~[tfmg-0.6.0e-1.20.1.jar%23223!/:0.6.0e-1.20.1]
	at com.drmangotea.tfmg.CreateTFMG.<init>(CreateTFMG.java:57) ~[tfmg-0.6.0e-1.20.1.jar%23223!/:0.6.0e-1.20.1]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.17.jar%23230!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.17.jar%23229!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at com.jozufozu.flywheel.core.StitchedSprite.<init>(StitchedSprite.java:24) ~[flywheel-forge-1.20.1-0.6.10-7.jar%23295!/:0.6.10-7]
	at com.jozufozu.flywheel.core.StitchedSprite.<init>(StitchedSprite.java:28) ~[flywheel-forge-1.20.1-0.6.10-7.jar%23295!/:0.6.10-7]
	at com.simibubi.create.foundation.block.render.SpriteShiftEntry.set(SpriteShiftEntry.java:13) ~[create-1.20.1-0.5.1.f.jar%23196!/:0.5.1.f]
	at com.simibubi.create.foundation.block.connected.CTSpriteShifter.lambda$getCT$0(CTSpriteShifter.java:22) ~[create-1.20.1-0.5.1.f.jar%23196!/:0.5.1.f]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.20.1-47.2.17.jar%23229!/:?]
	at com.simibubi.create.foundation.block.connected.CTSpriteShifter.getCT(CTSpriteShifter.java:22) ~[create-1.20.1-0.5.1.f.jar%23196!/:0.5.1.f]
	at com.drmangotea.tfmg.base.TFMGSpriteShifts.getCT(TFMGSpriteShifts.java:65) ~[tfmg-0.6.0e-1.20.1.jar%23223!/:0.6.0e-1.20.1]
	at com.drmangotea.tfmg.base.TFMGSpriteShifts.getCT(TFMGSpriteShifts.java:69) ~[tfmg-0.6.0e-1.20.1.jar%23223!/:0.6.0e-1.20.1]
	at com.drmangotea.tfmg.base.TFMGSpriteShifts.omni(TFMGSpriteShifts.java:53) ~[tfmg-0.6.0e-1.20.1.jar%23223!/:0.6.0e-1.20.1]
	at com.drmangotea.tfmg.base.TFMGSpriteShifts.<clinit>(TFMGSpriteShifts.java:12) ~[tfmg-0.6.0e-1.20.1.jar%23223!/:0.6.0e-1.20.1]
	... 16 more

Any idea is that come from your mod or not ?

**Comment by DrMango14** [comment]
i'd blame interactive for that one
